apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-flake-reporter"
  labels:
    {{- include "flakeReporter.labels" . | nindent 4 }}
spec:
  replicas: {{ default 2 .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "flakeReporter.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flakeReporter.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: flake-reporter
          image: {{ .Values.deployment.image }}
          ports:
            - containerPort: 9090
              name: http
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: FIRESTORE_PROJECT_ID
              value: {{ .Values.firestoreProjectId }}

            {{ if .Values.deployment.extraEnvVars }}
            {{- toYaml .Values.deployment.extraEnvVars | nindent 12 }}
            {{ end }}
        {{ if .Values.deployment.sidecars }}
        {{- toYaml .Values.deployment.sidecars | nindent 8 }}
        {{ end }}
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- toYaml .Values.deployment.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
      {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.priorityClass }}
      priorityClassName: {{ .Values.deployment.priorityClass }}
      {{- end }}
