apiVersion: v1
kind: Service
metadata:
  name: "{{.Release.Name}}-flake-reporter"
  labels:
    {{- include "flakeReporter.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "flakeReporter.labels" . | nindent 4 }}
