{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    {{ if .Values.serviceAccount.gcpServiceAccount }}
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}
    {{ end }}
  labels:
    {{- include "flakeReporter.labels" . | nindent 4 }}
{{- end }}
