{{ if .Values.serviceMonitor.enable }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{.Release.Name}}"
  labels:
    {{- include "flakeReporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "flakeReporter.labels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: 5m
    path: /metrics

{{ end }}
