name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      FIRESTORE_EMULATOR_HOST: "localhost:8080"

    services:
      firestore:
        image: pathmotion/firestore-emulator-docker
        ports: ["8080:8080"]
        env:
          FIRESTORE_PORT: 8080
          FIRESTORE_PROJECT_ID: test-project

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
